/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import modele.ModeleVip;
import metier.Nationalite;
import metier.Vip;

/**
 *
 * @author Guillaume
 */
public class MainScreen extends javax.swing.JFrame {

    private ModeleVip modeleVip;
    private Vip leVip;
    /**
     * Creates new form Tabulado
     */
    public MainScreen(ModeleVip modeleVip, String baseName) {
        this.modeleVip = modeleVip;

        initComponents();
       

        this.baseNameTxt.setText(baseName);
        try {
            modeleVip.loadVip();
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        eventTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        numVip = new javax.swing.JLabel();
        nomVip = new javax.swing.JLabel();
        prenomVip = new javax.swing.JLabel();
        numViptxt = new javax.swing.JTextField();
        nomViptxt = new javax.swing.JTextField();
        prenomViptxt = new javax.swing.JTextField();
        civiliteVip = new javax.swing.JLabel();
        civiliteVipbox = new javax.swing.JComboBox<>();
        naissanceVip = new javax.swing.JLabel();
        naissanceViptxt = new javax.swing.JTextField();
        roleVip = new javax.swing.JLabel();
        roleVipbox = new javax.swing.JComboBox<>();
        nationaliteVip = new javax.swing.JLabel();
        nationaliteVipbox = new javax.swing.JComboBox<>();
        statutVip = new javax.swing.JLabel();
        statutVipbox = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        baseIndicTxt = new javax.swing.JLabel();
        baseNameTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVip = new javax.swing.JTable();
        datenaissanceVip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        naissanceVip1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VoiceLa Administration Tool");
        setResizable(false);

        numVip.setText("Numéro VIP");

        nomVip.setText("Nom");

        prenomVip.setText("Prénom");

        numViptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numViptxtActionPerformed(evt);
            }
        });

        nomViptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomViptxtActionPerformed(evt);
            }
        });

        civiliteVip.setText("Civilité");

        civiliteVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "Mme", " " }));
        civiliteVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civiliteVipboxActionPerformed(evt);
            }
        });

        naissanceVip.setText("Date ");

        roleVip.setText("Rôle");

        roleVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "R", "AR" }));
        roleVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleVipboxActionPerformed(evt);
            }
        });

        nationaliteVip.setText("Nationalité");

        nationaliteVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FR" }));
        nationaliteVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationaliteVipboxActionPerformed(evt);
            }
        });

        statutVip.setText("Statut ");

        statutVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "D", "C" }));
        statutVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutVipboxActionPerformed(evt);
            }
        });

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross.png"))); // NOI18N
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrows.png"))); // NOI18N
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        baseIndicTxt.setText("Nom de la base : ");

        baseNameTxt.setText("Nom d'utilisateur");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableVip.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableVip.setModel(modeleVip);
        tableVip.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tableVip);

        jLabel1.setText("Ajouter à la base");

        jLabel2.setText("Réinitialiser les champs/actualiser la vue");

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Supprimer l'élément sélectionné");

        naissanceVip1.setText("Naissance (lieu)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(baseIndicTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseNameTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numVip)
                        .addGap(92, 92, 92)
                        .addComponent(numViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomVip)
                        .addGap(127, 127, 127)
                        .addComponent(nomViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prenomVip)
                        .addGap(112, 112, 112)
                        .addComponent(prenomViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(civiliteVip)
                        .addGap(117, 117, 117)
                        .addComponent(civiliteVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(naissanceVip1)
                        .addGap(73, 73, 73)
                        .addComponent(naissanceViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(naissanceVip)
                        .addGap(122, 122, 122)
                        .addComponent(datenaissanceVip, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(roleVip)
                        .addGap(127, 127, 127)
                        .addComponent(roleVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nationaliteVip)
                        .addGap(97, 97, 97)
                        .addComponent(nationaliteVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statutVip)
                        .addGap(115, 115, 115)
                        .addComponent(statutVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(baseIndicTxt)
                            .addComponent(baseNameTxt))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(numVip))
                            .addComponent(numViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nomVip))
                            .addComponent(nomViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(prenomVip))
                            .addComponent(prenomViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(civiliteVip))
                            .addComponent(civiliteVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(naissanceVip1))
                            .addComponent(naissanceViptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(datenaissanceVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(naissanceVip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(roleVip))
                            .addComponent(roleVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nationaliteVip))
                            .addComponent(nationaliteVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statutVip)
                            .addComponent(statutVipbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        eventTab.addTab("Gestion des VIP", new javax.swing.ImageIcon(getClass().getResource("/lux.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        eventTab.addTab("Gestion des photos", new javax.swing.ImageIcon(getClass().getResource("/photo.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        eventTab.addTab("Evènements", new javax.swing.ImageIcon(getClass().getResource("/medical.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        eventTab.addTab("Gestion des Films", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        eventTab.addTab("Gestion des Acteurs", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        eventTab.addTab("Gestion des Réalisateurs", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(eventTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        eventTab.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numViptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numViptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numViptxtActionPerformed

    private void nomViptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomViptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomViptxtActionPerformed

    private void civiliteVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civiliteVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civiliteVipboxActionPerformed

    private void roleVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleVipboxActionPerformed

    private void nationaliteVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationaliteVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationaliteVipboxActionPerformed

    private void statutVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statutVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statutVipboxActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {

            if (numViptxt.getText().isEmpty()) {
                throw new Exception("Le champ numéro doit pas être vide");
            }
            //leVip.setNumVip(numViptxt.getText());
            String a = numViptxt.getText();
            
            if (nomViptxt.getText().isEmpty()){
                throw new Exception("Le champ nom ne doit pas être vide");
            }
            //leVip.setNomVip(nomViptxt.getText());
            String b = nomViptxt.getText();
            
            if (prenomViptxt.getText().isEmpty()){
                throw new Exception("Le champ prénom ne doit pas être vide");
            }
            //leVip.setPrenomVip(prenomViptxt.getText());
            String c = prenomViptxt.getText();
            
            //leVip.setCivilite(civiliteVipbox.getSelectedItem().toString());
            String d = civiliteVipbox.getSelectedItem().toString();
            
            if (datenaissanceVip.getText().isEmpty()){
                throw new Exception("Ce champ ne doit pas être vide");
            }
            //leVip.setDateNaissance(datenaissanceVip.getText());
            String f = datenaissanceVip.getText();
            
            
            if (naissanceViptxt.getText().isEmpty()){
                throw new Exception("Ce champ ne doit pas être vide");
            }
            //leVip.setLieuNaissance(naissanceViptxt.getText());
            String e = naissanceViptxt.getText();
            
            //leVip.setCodeRole(roleVipbox.getSelectedItem().toString());
            String g = roleVipbox.getSelectedItem().toString();
            
            //leVip.setCodeStatut(statutVipbox.getSelectedItem().toString());
            String h = statutVipbox.getSelectedItem().toString();
            
            //leVip.setNationalite(nationaliteVipbox.getSelectedItem().toString());
            String i = nationaliteVipbox.getSelectedItem().toString();
            

            System.out.println(i);
            leVip = new Vip(a,b,c,d,e,f,g,h,i);
            modeleVip.addVip(leVip);
            
            JOptionPane.showMessageDialog(this, "Votre requête a bien été ajoutée à la base. ", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        numViptxt.setText("");
        nomViptxt.setText("");
        prenomViptxt.setText("");
        datenaissanceVip.setText("");
        naissanceViptxt.setText("");
        modeleVip.refreshVip();
        JOptionPane.showMessageDialog(this, "Les champs ont été réinitialisés et la vue actualisée.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        
        try {
            int ligne = tableVip.getSelectedRow();
            modeleVip.delVip(ligne);
            JOptionPane.showMessageDialog(this, "VIP supprimé avec succès ! ", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_delBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel baseIndicTxt;
    private javax.swing.JLabel baseNameTxt;
    private javax.swing.JLabel civiliteVip;
    private javax.swing.JComboBox<String> civiliteVipbox;
    private javax.swing.JTextField datenaissanceVip;
    private javax.swing.JButton delBtn;
    private javax.swing.JTabbedPane eventTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel naissanceVip;
    private javax.swing.JLabel naissanceVip1;
    private javax.swing.JTextField naissanceViptxt;
    private javax.swing.JLabel nationaliteVip;
    private javax.swing.JComboBox<String> nationaliteVipbox;
    private javax.swing.JLabel nomVip;
    private javax.swing.JTextField nomViptxt;
    private javax.swing.JLabel numVip;
    private javax.swing.JTextField numViptxt;
    private javax.swing.JLabel prenomVip;
    private javax.swing.JTextField prenomViptxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel roleVip;
    private javax.swing.JComboBox<String> roleVipbox;
    private javax.swing.JLabel statutVip;
    private javax.swing.JComboBox<String> statutVipbox;
    private javax.swing.JTable tableVip;
    // End of variables declaration//GEN-END:variables
}
