/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import modele.ModeleVip;
import metier.Nationalite;
import metier.Vip;

/**
 *
 * @author Guillaume
 */
public class MainScreen extends javax.swing.JFrame {

    private ModeleVip modeleVip;
    private Vip leVip;
    /**
     * Creates new form Tabulado
     */
    public MainScreen(ModeleVip modeleVip, String baseName) {
        this.modeleVip = modeleVip;

        initComponents();
       

        this.baseNameTxt.setText(baseName);
        try {
            modeleVip.loadVip();
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        eventTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        numVip = new javax.swing.JLabel();
        nomVip = new javax.swing.JLabel();
        prenomVip = new javax.swing.JLabel();
        numViptxt = new javax.swing.JTextField();
        nomViptxt = new javax.swing.JTextField();
        prenomViptxt = new javax.swing.JTextField();
        civiliteVip = new javax.swing.JLabel();
        civiliteVipbox = new javax.swing.JComboBox<>();
        naissanceVip = new javax.swing.JLabel();
        naissanceViptxt = new javax.swing.JTextField();
        roleVip = new javax.swing.JLabel();
        roleVipbox = new javax.swing.JComboBox<>();
        nationaliteVip = new javax.swing.JLabel();
        nationaliteVipbox = new javax.swing.JComboBox<>();
        statutVip = new javax.swing.JLabel();
        statutVipbox = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        baseIndicTxt = new javax.swing.JLabel();
        baseNameTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVip = new javax.swing.JTable();
        datenaissanceVip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VoiceLa Administration Tool");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numVip.setText("Numéro");
        jPanel1.add(numVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        nomVip.setText("Nom");
        jPanel1.add(nomVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        prenomVip.setText("Prénom");
        jPanel1.add(prenomVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        numViptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numViptxtActionPerformed(evt);
            }
        });
        jPanel1.add(numViptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 51, 124, -1));

        nomViptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomViptxtActionPerformed(evt);
            }
        });
        jPanel1.add(nomViptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 77, 124, -1));
        jPanel1.add(prenomViptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 103, 124, -1));

        civiliteVip.setText("Civilité");
        jPanel1.add(civiliteVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        civiliteVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "Mme", " " }));
        civiliteVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civiliteVipboxActionPerformed(evt);
            }
        });
        jPanel1.add(civiliteVipbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 129, 124, -1));

        naissanceVip.setText("Naissance (lieu)");
        jPanel1.add(naissanceVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));
        jPanel1.add(naissanceViptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 155, 124, -1));

        roleVip.setText("Rôle");
        jPanel1.add(roleVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        roleVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "R", "AR" }));
        roleVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleVipboxActionPerformed(evt);
            }
        });
        jPanel1.add(roleVipbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 207, 124, -1));

        nationaliteVip.setText("Nationalité");
        jPanel1.add(nationaliteVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 241, -1, -1));

        nationaliteVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FR" }));
        nationaliteVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationaliteVipboxActionPerformed(evt);
            }
        });
        jPanel1.add(nationaliteVipbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 238, 124, -1));

        statutVip.setText("Statut ");
        jPanel1.add(statutVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 276, -1, -1));

        statutVipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "D", "C" }));
        statutVipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutVipboxActionPerformed(evt);
            }
        });
        jPanel1.add(statutVipbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 276, 124, -1));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross.png"))); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 329, 31, -1));

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrows.png"))); // NOI18N
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 368, 31, -1));

        baseIndicTxt.setText("Nom de la base : ");
        jPanel1.add(baseIndicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        baseNameTxt.setText("Nom d'utilisateur");
        jPanel1.add(baseNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableVip.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableVip.setModel(modeleVip);
        tableVip.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tableVip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 11, 874, 472));
        jPanel1.add(datenaissanceVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 181, 124, -1));

        jLabel1.setText("Ajouter à la base");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel2.setText("Réinitialiser les champs/actualiser la vue");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel1.add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 31, -1));

        jLabel3.setText("Supprimer l'élément sélectionné");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 299, 10));

        eventTab.addTab("Gestion des VIP", new javax.swing.ImageIcon(getClass().getResource("/lux.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        eventTab.addTab("Gestion des photos", new javax.swing.ImageIcon(getClass().getResource("/photo.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        eventTab.addTab("Evènements", new javax.swing.ImageIcon(getClass().getResource("/medical.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(eventTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        eventTab.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numViptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numViptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numViptxtActionPerformed

    private void nomViptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomViptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomViptxtActionPerformed

    private void civiliteVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civiliteVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civiliteVipboxActionPerformed

    private void roleVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleVipboxActionPerformed

    private void nationaliteVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationaliteVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationaliteVipboxActionPerformed

    private void statutVipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statutVipboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statutVipboxActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {

            if (numViptxt.getText().isEmpty()) {
                throw new Exception("Le champ numéro doit pas être vide");
            }
            //leVip.setNumVip(numViptxt.getText());
            String a = numViptxt.getText();
            
            if (nomViptxt.getText().isEmpty()){
                throw new Exception("Le champ nom ne doit pas être vide");
            }
            //leVip.setNomVip(nomViptxt.getText());
            String b = nomViptxt.getText();
            
            if (prenomViptxt.getText().isEmpty()){
                throw new Exception("Le champ prénom ne doit pas être vide");
            }
            //leVip.setPrenomVip(prenomViptxt.getText());
            String c = prenomViptxt.getText();
            
            //leVip.setCivilite(civiliteVipbox.getSelectedItem().toString());
            String d = civiliteVipbox.getSelectedItem().toString();
            
            if (datenaissanceVip.getText().isEmpty()){
                throw new Exception("Ce champ ne doit pas être vide");
            }
            //leVip.setDateNaissance(datenaissanceVip.getText());
            String f = datenaissanceVip.getText();
            
            
            if (naissanceViptxt.getText().isEmpty()){
                throw new Exception("Ce champ ne doit pas être vide");
            }
            //leVip.setLieuNaissance(naissanceViptxt.getText());
            String e = naissanceViptxt.getText();
            
            //leVip.setCodeRole(roleVipbox.getSelectedItem().toString());
            String g = roleVipbox.getSelectedItem().toString();
            
            //leVip.setCodeStatut(statutVipbox.getSelectedItem().toString());
            String h = statutVipbox.getSelectedItem().toString();
            
            //leVip.setNationalite(nationaliteVipbox.getSelectedItem().toString());
            String i = nationaliteVipbox.getSelectedItem().toString();
            

            System.out.println(i);
            leVip = new Vip(a,b,c,d,e,f,g,h,i);
            modeleVip.addVip(leVip);
            
            JOptionPane.showMessageDialog(this, "Votre requête a bien été ajoutée à la base. ", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        numViptxt.setText("");
        nomViptxt.setText("");
        prenomViptxt.setText("");
        datenaissanceVip.setText("");
        naissanceViptxt.setText("");
        modeleVip.refreshVip();
        JOptionPane.showMessageDialog(this, "Les champs ont été réinitialisés et la vue actualisée.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        
        try {
            int ligne = tableVip.getSelectedRow();
            modeleVip.delVip(ligne);
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_delBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel baseIndicTxt;
    private javax.swing.JLabel baseNameTxt;
    private javax.swing.JLabel civiliteVip;
    private javax.swing.JComboBox<String> civiliteVipbox;
    private javax.swing.JTextField datenaissanceVip;
    private javax.swing.JButton delBtn;
    private javax.swing.JTabbedPane eventTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel naissanceVip;
    private javax.swing.JTextField naissanceViptxt;
    private javax.swing.JLabel nationaliteVip;
    private javax.swing.JComboBox<String> nationaliteVipbox;
    private javax.swing.JLabel nomVip;
    private javax.swing.JTextField nomViptxt;
    private javax.swing.JLabel numVip;
    private javax.swing.JTextField numViptxt;
    private javax.swing.JLabel prenomVip;
    private javax.swing.JTextField prenomViptxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel roleVip;
    private javax.swing.JComboBox<String> roleVipbox;
    private javax.swing.JLabel statutVip;
    private javax.swing.JComboBox<String> statutVipbox;
    private javax.swing.JTable tableVip;
    // End of variables declaration//GEN-END:variables
}
